// 한자 획수 데이터베이스 - 한국 작명에 자주 사용되는 한자
// 획수는 강희자전(康熙字典) 기준 정자체 획수를 사용합니다.
// 작명학에서 획수 1개 차이가 수리격 결과를 완전히 바꾸므로 정확성이 중요합니다.

export interface HanjaEntry {
  strokes: number;
  meaning: string;
  reading: string;
  element?: '木' | '火' | '土' | '金' | '水';
}

// ============================================================
// 남자 이름에 많이 쓰이는 한자
// ============================================================
const MALE_COMMON: Record<string, HanjaEntry> = {
  '俊': { strokes: 9, meaning: '준걸', reading: '준' },
  '成': { strokes: 7, meaning: '이룰', reading: '성' },
  '英': { strokes: 11, meaning: '꽃부리', reading: '영' },
  '民': { strokes: 5, meaning: '백성', reading: '민' },
  '泰': { strokes: 10, meaning: '클', reading: '태' },
  '浩': { strokes: 11, meaning: '넓을', reading: '호' },
  '宇': { strokes: 6, meaning: '집', reading: '우' },
  '賢': { strokes: 15, meaning: '어질', reading: '현' },
  '碩': { strokes: 14, meaning: '클', reading: '석' },
  '勳': { strokes: 16, meaning: '공', reading: '훈' },
  '赫': { strokes: 14, meaning: '빛날', reading: '혁' },
  '鎬': { strokes: 18, meaning: '호미', reading: '호' },
  '奎': { strokes: 9, meaning: '별', reading: '규' },
  '奐': { strokes: 9, meaning: '빛날', reading: '환' },
  '煥': { strokes: 13, meaning: '빛날', reading: '환' },
  '榮': { strokes: 14, meaning: '영화', reading: '영' },
  '哲': { strokes: 10, meaning: '밝을', reading: '철' },
  '豪': { strokes: 14, meaning: '호걸', reading: '호' },
  '雄': { strokes: 12, meaning: '수컷', reading: '웅' },
  '龍': { strokes: 16, meaning: '용', reading: '용' },
  '虎': { strokes: 8, meaning: '범', reading: '호' },
  '範': { strokes: 15, meaning: '법', reading: '범' },
  '翰': { strokes: 16, meaning: '깃', reading: '한' },
  '鉉': { strokes: 13, meaning: '쇠', reading: '현' },
  '彬': { strokes: 11, meaning: '빛날', reading: '빈' },
  '憲': { strokes: 16, meaning: '법', reading: '헌' },
  '燮': { strokes: 17, meaning: '불꽃', reading: '섭' },
  '鍾': { strokes: 17, meaning: '쇠북', reading: '종' },
  '濬': { strokes: 18, meaning: '깊을', reading: '준' },
  '旭': { strokes: 6, meaning: '아침 해', reading: '욱' },
  '昊': { strokes: 8, meaning: '하늘', reading: '호' },
  '昇': { strokes: 8, meaning: '오를', reading: '승' },
  '晟': { strokes: 11, meaning: '밝을', reading: '성' },
  '晧': { strokes: 11, meaning: '밝을', reading: '호' },
  '暻': { strokes: 13, meaning: '밝을', reading: '경' },
  '曙': { strokes: 18, meaning: '새벽', reading: '서' },
  '朗': { strokes: 11, meaning: '밝을', reading: '랑' },
  '杰': { strokes: 8, meaning: '뛰어날', reading: '걸' },
  '棟': { strokes: 12, meaning: '마룻대', reading: '동' },
  '楠': { strokes: 13, meaning: '남나무', reading: '남' },
  '權': { strokes: 22, meaning: '권세', reading: '권' },
  '漢': { strokes: 15, meaning: '한수', reading: '한' },
  '瀚': { strokes: 20, meaning: '넓을', reading: '한' },
  '烈': { strokes: 10, meaning: '세찰', reading: '렬' },
  '熙': { strokes: 13, meaning: '빛날', reading: '희' },
  '璋': { strokes: 16, meaning: '구슬', reading: '장' },
  '男': { strokes: 7, meaning: '사내', reading: '남' },
  '丈': { strokes: 3, meaning: '어른', reading: '장' },
  '剛': { strokes: 10, meaning: '굳셀', reading: '강' },
  '勇': { strokes: 9, meaning: '날랠', reading: '용' },
  '堅': { strokes: 11, meaning: '굳을', reading: '견' },
  '威': { strokes: 9, meaning: '위엄', reading: '위' },
  '尙': { strokes: 8, meaning: '오히려', reading: '상' },
  '嶽': { strokes: 17, meaning: '큰 산', reading: '악' },
  '廷': { strokes: 7, meaning: '조정', reading: '정' },
  '彰': { strokes: 14, meaning: '드러날', reading: '창' },
  '承': { strokes: 8, meaning: '이을', reading: '승' },
  '敬': { strokes: 13, meaning: '공경할', reading: '경' },
  '斌': { strokes: 12, meaning: '빛날', reading: '빈' },
  '昌': { strokes: 8, meaning: '창성할', reading: '창' },
  '晉': { strokes: 10, meaning: '나아갈', reading: '진' },
  '武': { strokes: 8, meaning: '호반', reading: '무' },
  '炳': { strokes: 9, meaning: '밝을', reading: '병' },
  '燦': { strokes: 17, meaning: '빛날', reading: '찬' },
  '珏': { strokes: 10, meaning: '쌍옥', reading: '각' },
  '璿': { strokes: 17, meaning: '옥', reading: '선' },
  '祐': { strokes: 10, meaning: '도울', reading: '우' },
  '禹': { strokes: 9, meaning: '우임금', reading: '우' },
  '竣': { strokes: 12, meaning: '마칠', reading: '준' },
  '翊': { strokes: 11, meaning: '도울', reading: '익' },
  '胤': { strokes: 9, meaning: '자손', reading: '윤' },
  '衡': { strokes: 16, meaning: '저울', reading: '형' },
  '載': { strokes: 13, meaning: '실을', reading: '재' },
  '鎭': { strokes: 18, meaning: '진압할', reading: '진' },
  '騰': { strokes: 20, meaning: '오를', reading: '등' },
};

// ============================================================
// 여자 이름에 많이 쓰이는 한자
// ============================================================
const FEMALE_COMMON: Record<string, HanjaEntry> = {
  '美': { strokes: 9, meaning: '아름다울', reading: '미' },
  '恩': { strokes: 10, meaning: '은혜', reading: '은' },
  '智': { strokes: 12, meaning: '지혜', reading: '지' },
  '秀': { strokes: 7, meaning: '빼어날', reading: '수' },
  '娟': { strokes: 10, meaning: '고울', reading: '연' },
  '雅': { strokes: 12, meaning: '우아할', reading: '아' },
  '瑛': { strokes: 14, meaning: '옥빛', reading: '영' },
  '淑': { strokes: 12, meaning: '맑을', reading: '숙' },
  '貞': { strokes: 9, meaning: '곧을', reading: '정' },
  '惠': { strokes: 12, meaning: '은혜', reading: '혜' },
  '姬': { strokes: 10, meaning: '계집', reading: '희' },
  '嬉': { strokes: 15, meaning: '기뻐할', reading: '희' },
  '嬌': { strokes: 15, meaning: '아리따울', reading: '교' },
  '嫻': { strokes: 15, meaning: '고울', reading: '한' },
  '媛': { strokes: 12, meaning: '미인', reading: '원' },
  '妍': { strokes: 7, meaning: '고울', reading: '연' },
  '姸': { strokes: 9, meaning: '고울', reading: '연' },
  '婉': { strokes: 11, meaning: '얌전할', reading: '완' },
  '娥': { strokes: 10, meaning: '아름다울', reading: '아' },
  '嫣': { strokes: 14, meaning: '곱고 예쁠', reading: '언' },
  '婷': { strokes: 12, meaning: '아리따울', reading: '정' },
  '姝': { strokes: 9, meaning: '아름다울', reading: '주' },
  '娜': { strokes: 10, meaning: '아리따울', reading: '나' },
  '珠': { strokes: 11, meaning: '구슬', reading: '주' },
  '琳': { strokes: 13, meaning: '옥', reading: '림' },
  '瑤': { strokes: 15, meaning: '아름다운 옥', reading: '요' },
  '瑾': { strokes: 16, meaning: '옥 이름', reading: '근' },
  '璃': { strokes: 15, meaning: '유리', reading: '리' },
  '琬': { strokes: 13, meaning: '아름다운 옥', reading: '완' },
  '珉': { strokes: 10, meaning: '옥돌', reading: '민' },
  '瑞': { strokes: 14, meaning: '상서로울', reading: '서' },
  '玲': { strokes: 10, meaning: '옥소리', reading: '령' },
  '瑜': { strokes: 14, meaning: '아름다운 옥', reading: '유' },
  '芳': { strokes: 10, meaning: '꽃다울', reading: '방' },
  '蓮': { strokes: 17, meaning: '연꽃', reading: '련' },
  '蘭': { strokes: 23, meaning: '난초', reading: '란' },
  '薇': { strokes: 19, meaning: '고비', reading: '미' },
  '萱': { strokes: 15, meaning: '원추리', reading: '훤' },
  '蕙': { strokes: 18, meaning: '혜초', reading: '혜' },
  '菁': { strokes: 14, meaning: '부추', reading: '정' },
  '茹': { strokes: 12, meaning: '먹을', reading: '여' },
  '莉': { strokes: 13, meaning: '재스민', reading: '리' },
  '荷': { strokes: 13, meaning: '연꽃', reading: '하' },
  '苑': { strokes: 11, meaning: '동산', reading: '원' },
  '彩': { strokes: 11, meaning: '채색', reading: '채' },
  '紗': { strokes: 10, meaning: '비단', reading: '사' },
  '絢': { strokes: 12, meaning: '빛날', reading: '현' },
  '綺': { strokes: 14, meaning: '아름다울', reading: '기' },
  '緣': { strokes: 15, meaning: '인연', reading: '연' },
  '羅': { strokes: 19, meaning: '비단', reading: '라' },
  '允': { strokes: 4, meaning: '진실로', reading: '윤' },
  '丹': { strokes: 4, meaning: '붉을', reading: '단' },
  '侑': { strokes: 8, meaning: '도울', reading: '유' },
  '倫': { strokes: 10, meaning: '인륜', reading: '륜' },
  '凜': { strokes: 15, meaning: '찰', reading: '름' },
  '叡': { strokes: 16, meaning: '슬기로울', reading: '예' },
  '嘉': { strokes: 14, meaning: '아름다울', reading: '가' },
  '喜': { strokes: 12, meaning: '기쁠', reading: '희' },
  '夢': { strokes: 14, meaning: '꿈', reading: '몽' },
  '奈': { strokes: 8, meaning: '어찌', reading: '나' },
  '妃': { strokes: 6, meaning: '왕비', reading: '비' },
  '姮': { strokes: 9, meaning: '항아', reading: '항' },
  '嬅': { strokes: 14, meaning: '고울', reading: '화' },
  '孝': { strokes: 7, meaning: '효도', reading: '효' },
  '宣': { strokes: 9, meaning: '베풀', reading: '선' },
  '尹': { strokes: 4, meaning: '다스릴', reading: '윤' },
  '悅': { strokes: 11, meaning: '기쁠', reading: '열' },
  '愛': { strokes: 13, meaning: '사랑', reading: '애' },
  '慧': { strokes: 15, meaning: '슬기로울', reading: '혜' },
  '抒': { strokes: 8, meaning: '펼', reading: '서' },
  '敃': { strokes: 9, meaning: '힘쓸', reading: '민' },
  '晶': { strokes: 12, meaning: '수정', reading: '정' },
  '曦': { strokes: 20, meaning: '햇빛', reading: '희' },
  '柔': { strokes: 9, meaning: '부드러울', reading: '유' },
  '栩': { strokes: 10, meaning: '상수리', reading: '우' },
  '梓': { strokes: 11, meaning: '가래나무', reading: '재' },
  '楹': { strokes: 13, meaning: '기둥', reading: '영' },
  '沅': { strokes: 8, meaning: '강이름', reading: '원' },
  '潤': { strokes: 16, meaning: '윤택할', reading: '윤' },
  '瀅': { strokes: 19, meaning: '맑을', reading: '형' },
  '煐': { strokes: 13, meaning: '빛날', reading: '영' },
  '瑗': { strokes: 14, meaning: '옥고리', reading: '원' },
  '穗': { strokes: 17, meaning: '이삭', reading: '수' },
  '筠': { strokes: 13, meaning: '대껍질', reading: '균' },
  '粹': { strokes: 14, meaning: '순수할', reading: '수' },
  '縝': { strokes: 16, meaning: '고울', reading: '진' },
  '翠': { strokes: 14, meaning: '비취', reading: '취' },
  '舒': { strokes: 12, meaning: '펼', reading: '서' },
  '苡': { strokes: 11, meaning: '율무', reading: '이' },
  '葉': { strokes: 15, meaning: '잎', reading: '엽' },
  '詩': { strokes: 13, meaning: '시', reading: '시' },
  '諳': { strokes: 16, meaning: '익힐', reading: '암' },
  '賓': { strokes: 14, meaning: '손님', reading: '빈' },
  '頌': { strokes: 13, meaning: '칭송할', reading: '송' },
  '馥': { strokes: 18, meaning: '향기로울', reading: '복' },
};

// ============================================================
// 성별 무관 공용 한자
// ============================================================
const UNISEX_COMMON: Record<string, HanjaEntry> = {
  '光': { strokes: 6, meaning: '빛', reading: '광' },
  '永': { strokes: 5, meaning: '길', reading: '영' },
  '善': { strokes: 12, meaning: '착할', reading: '선' },
  '正': { strokes: 5, meaning: '바를', reading: '정' },
  '仁': { strokes: 4, meaning: '어질', reading: '인' },
  '德': { strokes: 15, meaning: '큰', reading: '덕' },
  '和': { strokes: 8, meaning: '화할', reading: '화' },
  '義': { strokes: 13, meaning: '옳을', reading: '의' },
  '禮': { strokes: 18, meaning: '예도', reading: '례' },
  '信': { strokes: 9, meaning: '믿을', reading: '신' },
  '忠': { strokes: 8, meaning: '충성', reading: '충' },
  '孝': { strokes: 7, meaning: '효도', reading: '효' },
  '誠': { strokes: 14, meaning: '정성', reading: '성' },
  '道': { strokes: 13, meaning: '길', reading: '도' },
  '志': { strokes: 7, meaning: '뜻', reading: '지' },
  '文': { strokes: 4, meaning: '글', reading: '문' },
  '學': { strokes: 16, meaning: '배울', reading: '학' },
  '知': { strokes: 8, meaning: '알', reading: '지' },
  '明': { strokes: 8, meaning: '밝을', reading: '명' },
  '日': { strokes: 4, meaning: '날', reading: '일' },
  '月': { strokes: 4, meaning: '달', reading: '월' },
  '星': { strokes: 9, meaning: '별', reading: '성' },
  '天': { strokes: 4, meaning: '하늘', reading: '천' },
  '地': { strokes: 6, meaning: '땅', reading: '지' },
  '山': { strokes: 3, meaning: '산', reading: '산' },
  '石': { strokes: 5, meaning: '돌', reading: '석' },
  '玉': { strokes: 5, meaning: '구슬', reading: '옥' },
  '金': { strokes: 8, meaning: '쇠', reading: '금' },
  '一': { strokes: 1, meaning: '한', reading: '일' },
  '三': { strokes: 3, meaning: '석', reading: '삼' },
  '中': { strokes: 4, meaning: '가운데', reading: '중' },
  '大': { strokes: 3, meaning: '클', reading: '대' },
  '安': { strokes: 6, meaning: '편안', reading: '안' },
  '定': { strokes: 8, meaning: '정할', reading: '정' },
  '寧': { strokes: 14, meaning: '편안할', reading: '녕' },
  '平': { strokes: 5, meaning: '평평할', reading: '평' },
  '福': { strokes: 14, meaning: '복', reading: '복' },
  '祥': { strokes: 11, meaning: '상서로울', reading: '상' },
  '壽': { strokes: 14, meaning: '목숨', reading: '수' },
  '康': { strokes: 11, meaning: '편안할', reading: '강' },
  '泳': { strokes: 9, meaning: '헤엄칠', reading: '영' },
  '然': { strokes: 12, meaning: '그러할', reading: '연' },
  '聖': { strokes: 13, meaning: '성인', reading: '성' },
  '容': { strokes: 10, meaning: '얼굴', reading: '용' },
  '才': { strokes: 3, meaning: '재주', reading: '재' },
  '賢': { strokes: 15, meaning: '어질', reading: '현' },
  '恒': { strokes: 10, meaning: '항상', reading: '항' },
  '常': { strokes: 11, meaning: '항상', reading: '상' },
  '潤': { strokes: 16, meaning: '윤택할', reading: '윤' },
  '淨': { strokes: 12, meaning: '깨끗할', reading: '정' },
  '滿': { strokes: 15, meaning: '가득 찰', reading: '만' },
  '溫': { strokes: 14, meaning: '따뜻할', reading: '온' },
  '澄': { strokes: 16, meaning: '맑을', reading: '징' },
  '白': { strokes: 5, meaning: '흰', reading: '백' },
  '百': { strokes: 6, meaning: '일백', reading: '백' },
  '千': { strokes: 3, meaning: '일천', reading: '천' },
  '萬': { strokes: 15, meaning: '일만', reading: '만' },
  '世': { strokes: 5, meaning: '세상', reading: '세' },
  '久': { strokes: 3, meaning: '오랠', reading: '구' },
  '元': { strokes: 4, meaning: '으뜸', reading: '원' },
  '亨': { strokes: 7, meaning: '형통할', reading: '형' },
  '利': { strokes: 7, meaning: '이로울', reading: '리' },
  '吉': { strokes: 6, meaning: '길할', reading: '길' },
  '有': { strokes: 6, meaning: '있을', reading: '유' },
  '朝': { strokes: 12, meaning: '아침', reading: '조' },
  '暎': { strokes: 13, meaning: '비칠', reading: '영' },
  '敏': { strokes: 11, meaning: '민첩할', reading: '민' },
  '喆': { strokes: 12, meaning: '밝을', reading: '철' },
  '彗': { strokes: 11, meaning: '혜성', reading: '혜' },
  '昕': { strokes: 8, meaning: '밝을', reading: '흔' },
  '晏': { strokes: 10, meaning: '편안할', reading: '안' },
  '暉': { strokes: 13, meaning: '빛날', reading: '휘' },
  '曜': { strokes: 18, meaning: '빛날', reading: '요' },
  '朋': { strokes: 8, meaning: '벗', reading: '붕' },
  '來': { strokes: 8, meaning: '올', reading: '래' },
  '東': { strokes: 8, meaning: '동녘', reading: '동' },
  '南': { strokes: 9, meaning: '남녘', reading: '남' },
  '西': { strokes: 6, meaning: '서녘', reading: '서' },
  '北': { strokes: 5, meaning: '북녘', reading: '북' },
  '春': { strokes: 9, meaning: '봄', reading: '춘' },
  '夏': { strokes: 10, meaning: '여름', reading: '하' },
  '秋': { strokes: 9, meaning: '가을', reading: '추' },
  '冬': { strokes: 5, meaning: '겨울', reading: '동' },
  '新': { strokes: 13, meaning: '새', reading: '신' },
  '眞': { strokes: 10, meaning: '참', reading: '진' },
  '理': { strokes: 12, meaning: '다스릴', reading: '리' },
  '昱': { strokes: 9, meaning: '빛날', reading: '욱' },
  '峻': { strokes: 10, meaning: '높을', reading: '준' },
  '延': { strokes: 7, meaning: '늘일', reading: '연' },
  '修': { strokes: 10, meaning: '닦을', reading: '수' },
  '亮': { strokes: 9, meaning: '밝을', reading: '량' },
  '彥': { strokes: 9, meaning: '선비', reading: '언' },
  '景': { strokes: 12, meaning: '볕', reading: '경' },
  '博': { strokes: 12, meaning: '넓을', reading: '박' },
  '厚': { strokes: 9, meaning: '두터울', reading: '후' },
  '慶': { strokes: 15, meaning: '경사', reading: '경' },
  '祿': { strokes: 13, meaning: '녹', reading: '록' },
  '逸': { strokes: 15, meaning: '편안할', reading: '일' },
  '兌': { strokes: 7, meaning: '기쁠', reading: '태' },
  '亦': { strokes: 6, meaning: '또', reading: '역' },
  '云': { strokes: 4, meaning: '이를', reading: '운' },
  '亙': { strokes: 6, meaning: '걸칠', reading: '긍' },
  '令': { strokes: 5, meaning: '하여금', reading: '령' },
  '兆': { strokes: 6, meaning: '조짐', reading: '조' },
};

// ============================================================
// 오행별 한자 (木 / 火 / 土 / 金 / 水)
// ============================================================
const WOOD_ELEMENT: Record<string, HanjaEntry> = {
  '林': { strokes: 8, meaning: '수풀', reading: '림' },
  '松': { strokes: 8, meaning: '소나무', reading: '송' },
  '柏': { strokes: 9, meaning: '잣나무', reading: '백' },
  '森': { strokes: 12, meaning: '수풀', reading: '삼' },
  '木': { strokes: 4, meaning: '나무', reading: '목' },
  '桂': { strokes: 10, meaning: '계수나무', reading: '계' },
  '梅': { strokes: 11, meaning: '매화', reading: '매' },
  '竹': { strokes: 6, meaning: '대', reading: '죽' },
  '花': { strokes: 8, meaning: '꽃', reading: '화' },
  '茂': { strokes: 11, meaning: '무성할', reading: '무' },
  '根': { strokes: 10, meaning: '뿌리', reading: '근' },
  '樹': { strokes: 16, meaning: '나무', reading: '수' },
  '柱': { strokes: 9, meaning: '기둥', reading: '주' },
  '棠': { strokes: 12, meaning: '아가위', reading: '당' },
  '楊': { strokes: 13, meaning: '버들', reading: '양' },
  '榮': { strokes: 14, meaning: '영화', reading: '영' },
  '槿': { strokes: 15, meaning: '무궁화', reading: '근' },
  '樺': { strokes: 16, meaning: '자작나무', reading: '화' },
  '栢': { strokes: 10, meaning: '잣나무', reading: '백' },
  '杉': { strokes: 7, meaning: '삼나무', reading: '삼' },
  '桓': { strokes: 10, meaning: '기둥', reading: '환' },
  '柳': { strokes: 9, meaning: '버들', reading: '류' },
  '椿': { strokes: 13, meaning: '참죽나무', reading: '춘' },
  '欣': { strokes: 8, meaning: '기쁠', reading: '흔' },
  '芝': { strokes: 10, meaning: '지초', reading: '지' },
  '菊': { strokes: 14, meaning: '국화', reading: '국' },
  '蔚': { strokes: 17, meaning: '무성할', reading: '울' },
  '藝': { strokes: 21, meaning: '재주', reading: '예' },
  '蒼': { strokes: 16, meaning: '푸를', reading: '창' },
  '葦': { strokes: 15, meaning: '갈대', reading: '위' },
  '荃': { strokes: 12, meaning: '향초', reading: '전' },
};

const FIRE_ELEMENT: Record<string, HanjaEntry> = {
  '炳': { strokes: 9, meaning: '밝을', reading: '병' },
  '烈': { strokes: 10, meaning: '세찰', reading: '렬' },
  '焕': { strokes: 11, meaning: '빛날', reading: '환' },
  '炫': { strokes: 9, meaning: '빛날', reading: '현' },
  '曄': { strokes: 15, meaning: '빛날', reading: '엽' },
  '炅': { strokes: 8, meaning: '빛날', reading: '경' },
  '晨': { strokes: 11, meaning: '새벽', reading: '신' },
  '曉': { strokes: 16, meaning: '새벽', reading: '효' },
  '燦': { strokes: 17, meaning: '빛날', reading: '찬' },
  '煥': { strokes: 13, meaning: '빛날', reading: '환' },
  '熒': { strokes: 11, meaning: '반딧불', reading: '형' },
  '烽': { strokes: 11, meaning: '봉화', reading: '봉' },
  '燁': { strokes: 16, meaning: '빛날', reading: '엽' },
  '煜': { strokes: 13, meaning: '빛날', reading: '욱' },
  '熹': { strokes: 16, meaning: '빛날', reading: '희' },
  '照': { strokes: 13, meaning: '비출', reading: '조' },
  '煌': { strokes: 13, meaning: '빛날', reading: '황' },
  '熠': { strokes: 15, meaning: '빛날', reading: '읍' },
  '焰': { strokes: 12, meaning: '불꽃', reading: '염' },
  '燈': { strokes: 16, meaning: '등', reading: '등' },
  '爀': { strokes: 13, meaning: '빛날', reading: '혁' },
  '炘': { strokes: 8, meaning: '빛날', reading: '흔' },
  '灝': { strokes: 25, meaning: '넓을', reading: '호' },
};

const EARTH_ELEMENT: Record<string, HanjaEntry> = {
  '坤': { strokes: 8, meaning: '땅', reading: '곤' },
  '培': { strokes: 11, meaning: '북돋울', reading: '배' },
  '基': { strokes: 11, meaning: '터', reading: '기' },
  '垠': { strokes: 9, meaning: '언덕', reading: '은' },
  '堯': { strokes: 12, meaning: '높을', reading: '요' },
  '壇': { strokes: 16, meaning: '단', reading: '단' },
  '城': { strokes: 10, meaning: '성', reading: '성' },
  '域': { strokes: 11, meaning: '지경', reading: '역' },
  '堅': { strokes: 11, meaning: '굳을', reading: '견' },
  '塤': { strokes: 13, meaning: '훈', reading: '훈' },
  '境': { strokes: 14, meaning: '지경', reading: '경' },
  '墉': { strokes: 14, meaning: '담', reading: '용' },
  '壁': { strokes: 16, meaning: '벽', reading: '벽' },
  '均': { strokes: 7, meaning: '고를', reading: '균' },
  '堂': { strokes: 11, meaning: '집', reading: '당' },
  '塗': { strokes: 13, meaning: '바를', reading: '도' },
  '填': { strokes: 13, meaning: '메울', reading: '전' },
  '壘': { strokes: 18, meaning: '보루', reading: '루' },
  '坪': { strokes: 8, meaning: '평평할', reading: '평' },
  '垣': { strokes: 9, meaning: '담', reading: '원' },
  '埈': { strokes: 10, meaning: '높을', reading: '준' },
};

const METAL_ELEMENT: Record<string, HanjaEntry> = {
  '鑫': { strokes: 24, meaning: '쇠가 많음', reading: '흠' },
  '錫': { strokes: 16, meaning: '주석', reading: '석' },
  '銀': { strokes: 14, meaning: '은', reading: '은' },
  '鉉': { strokes: 13, meaning: '쇠', reading: '현' },
  '鐘': { strokes: 20, meaning: '쇠북', reading: '종' },
  '鍊': { strokes: 17, meaning: '쇠불릴', reading: '련' },
  '珍': { strokes: 10, meaning: '보배', reading: '진' },
  '寶': { strokes: 20, meaning: '보배', reading: '보' },
  '鋼': { strokes: 16, meaning: '쇠', reading: '강' },
  '銅': { strokes: 14, meaning: '구리', reading: '동' },
  '鎧': { strokes: 18, meaning: '갑옷', reading: '개' },
  '鑛': { strokes: 23, meaning: '쇳돌', reading: '광' },
  '鋒': { strokes: 15, meaning: '칼끝', reading: '봉' },
  '鍚': { strokes: 17, meaning: '도금', reading: '양' },
  '鉐': { strokes: 13, meaning: '돌', reading: '석' },
  '鑄': { strokes: 22, meaning: '부을', reading: '주' },
  '鍛': { strokes: 17, meaning: '쇠불릴', reading: '단' },
  '釗': { strokes: 10, meaning: '힘쓸', reading: '조' },
  '鈺': { strokes: 13, meaning: '보배', reading: '옥' },
  '銓': { strokes: 14, meaning: '저울질', reading: '전' },
  '鉅': { strokes: 13, meaning: '클', reading: '거' },
  '鎔': { strokes: 18, meaning: '녹일', reading: '용' },
  '鎭': { strokes: 18, meaning: '진압할', reading: '진' },
};

const WATER_ELEMENT: Record<string, HanjaEntry> = {
  '泳': { strokes: 9, meaning: '헤엄칠', reading: '영' },
  '洙': { strokes: 10, meaning: '물이름', reading: '수' },
  '海': { strokes: 11, meaning: '바다', reading: '해' },
  '澤': { strokes: 17, meaning: '못', reading: '택' },
  '潤': { strokes: 16, meaning: '윤택할', reading: '윤' },
  '涵': { strokes: 12, meaning: '잠길', reading: '함' },
  '源': { strokes: 14, meaning: '근원', reading: '원' },
  '淸': { strokes: 12, meaning: '맑을', reading: '청' },
  '泉': { strokes: 9, meaning: '샘', reading: '천' },
  '湖': { strokes: 13, meaning: '호수', reading: '호' },
  '濬': { strokes: 18, meaning: '깊을', reading: '준' },
  '河': { strokes: 9, meaning: '물', reading: '하' },
  '汀': { strokes: 6, meaning: '물가', reading: '정' },
  '沐': { strokes: 8, meaning: '머리감을', reading: '목' },
  '沛': { strokes: 8, meaning: '큰비', reading: '패' },
  '洋': { strokes: 10, meaning: '큰바다', reading: '양' },
  '洛': { strokes: 10, meaning: '강이름', reading: '락' },
  '津': { strokes: 10, meaning: '나루', reading: '진' },
  '浚': { strokes: 11, meaning: '깊을', reading: '준' },
  '淳': { strokes: 12, meaning: '순박할', reading: '순' },
  '淵': { strokes: 12, meaning: '못', reading: '연' },
  '渝': { strokes: 13, meaning: '변할', reading: '유' },
  '溪': { strokes: 14, meaning: '시내', reading: '계' },
  '漢': { strokes: 15, meaning: '한수', reading: '한' },
  '澈': { strokes: 16, meaning: '맑을', reading: '철' },
  '瀞': { strokes: 19, meaning: '맑을', reading: '정' },
  '灣': { strokes: 26, meaning: '물굽이', reading: '만' },
  '汝': { strokes: 7, meaning: '너', reading: '여' },
  '沃': { strokes: 8, meaning: '기름질', reading: '옥' },
  '池': { strokes: 7, meaning: '못', reading: '지' },
  '沅': { strokes: 8, meaning: '강이름', reading: '원' },
  '泓': { strokes: 9, meaning: '못', reading: '굉' },
  '洪': { strokes: 10, meaning: '넓을', reading: '홍' },
  '浩': { strokes: 11, meaning: '넓을', reading: '호' },
  '涉': { strokes: 11, meaning: '건널', reading: '섭' },
  '淮': { strokes: 12, meaning: '강이름', reading: '회' },
  '渲': { strokes: 13, meaning: '물들일', reading: '선' },
  '溢': { strokes: 14, meaning: '넘칠', reading: '일' },
  '漫': { strokes: 15, meaning: '넘칠', reading: '만' },
  '潔': { strokes: 16, meaning: '깨끗할', reading: '결' },
  '澗': { strokes: 17, meaning: '시내', reading: '간' },
  '濟': { strokes: 18, meaning: '건널', reading: '제' },
  '瀑': { strokes: 19, meaning: '폭포', reading: '폭' },
};

// ============================================================
// 흔한 성씨 한자
// ============================================================
const SURNAMES: Record<string, HanjaEntry> = {
  '金': { strokes: 8, meaning: '쇠', reading: '김' },
  '李': { strokes: 7, meaning: '자두', reading: '이' },
  '朴': { strokes: 6, meaning: '성', reading: '박' },
  '崔': { strokes: 11, meaning: '높을', reading: '최' },
  '鄭': { strokes: 15, meaning: '나라', reading: '정' },
  '姜': { strokes: 9, meaning: '생강', reading: '강' },
  '趙': { strokes: 14, meaning: '나라', reading: '조' },
  '尹': { strokes: 4, meaning: '다스릴', reading: '윤' },
  '張': { strokes: 11, meaning: '베풀', reading: '장' },
  '林': { strokes: 8, meaning: '수풀', reading: '임' },
  '韓': { strokes: 17, meaning: '나라', reading: '한' },
  '吳': { strokes: 7, meaning: '나라', reading: '오' },
  '徐': { strokes: 10, meaning: '천천히', reading: '서' },
  '申': { strokes: 5, meaning: '펼', reading: '신' },
  '權': { strokes: 22, meaning: '권세', reading: '권' },
  '黃': { strokes: 12, meaning: '누를', reading: '황' },
  '安': { strokes: 6, meaning: '편안', reading: '안' },
  '宋': { strokes: 7, meaning: '나라', reading: '송' },
  '柳': { strokes: 9, meaning: '버들', reading: '류' },
  '全': { strokes: 6, meaning: '온전할', reading: '전' },
  '洪': { strokes: 10, meaning: '넓을', reading: '홍' },
  '劉': { strokes: 15, meaning: '죽일', reading: '유' },
  '高': { strokes: 10, meaning: '높을', reading: '고' },
  '文': { strokes: 4, meaning: '글', reading: '문' },
  '孫': { strokes: 10, meaning: '손자', reading: '손' },
  '梁': { strokes: 11, meaning: '들보', reading: '양' },
  '裵': { strokes: 14, meaning: '나눌', reading: '배' },
  '曺': { strokes: 11, meaning: '무리', reading: '조' },
  '白': { strokes: 5, meaning: '흰', reading: '백' },
  '許': { strokes: 11, meaning: '허락할', reading: '허' },
  '南': { strokes: 9, meaning: '남녘', reading: '남' },
  '沈': { strokes: 8, meaning: '잠길', reading: '심' },
  '盧': { strokes: 16, meaning: '그릇', reading: '노' },
  '河': { strokes: 9, meaning: '물', reading: '하' },
  '田': { strokes: 5, meaning: '밭', reading: '전' },
  '車': { strokes: 7, meaning: '수레', reading: '차' },
  '朱': { strokes: 6, meaning: '붉을', reading: '주' },
  '丁': { strokes: 2, meaning: '고무래', reading: '정' },
  '具': { strokes: 8, meaning: '갖출', reading: '구' },
  '任': { strokes: 6, meaning: '맡길', reading: '임' },
  '兪': { strokes: 9, meaning: '대답', reading: '유' },
  '閔': { strokes: 12, meaning: '근심할', reading: '민' },
  '蔡': { strokes: 17, meaning: '나라', reading: '채' },
  '成': { strokes: 7, meaning: '이룰', reading: '성' },
  '陳': { strokes: 11, meaning: '진칠', reading: '진' },
  '嚴': { strokes: 20, meaning: '엄할', reading: '엄' },
  '元': { strokes: 4, meaning: '으뜸', reading: '원' },
  '邊': { strokes: 19, meaning: '가', reading: '변' },
  '廉': { strokes: 13, meaning: '청렴할', reading: '렴' },
  '魏': { strokes: 18, meaning: '나라', reading: '위' },
  '蘇': { strokes: 22, meaning: '소생할', reading: '소' },
  '羅': { strokes: 19, meaning: '비단', reading: '라' },
  '毛': { strokes: 4, meaning: '터럭', reading: '모' },
  '禹': { strokes: 9, meaning: '우임금', reading: '우' },
  '陸': { strokes: 11, meaning: '뭍', reading: '육' },
  '太': { strokes: 4, meaning: '클', reading: '태' },
  '鳩': { strokes: 13, meaning: '비둘기', reading: '구' },
  '奉': { strokes: 8, meaning: '받들', reading: '봉' },
  '玄': { strokes: 5, meaning: '검을', reading: '현' },
  '方': { strokes: 4, meaning: '모', reading: '방' },
  '呂': { strokes: 7, meaning: '성', reading: '여' },
  '芮': { strokes: 10, meaning: '풀이름', reading: '예' },
  '邱': { strokes: 8, meaning: '언덕', reading: '구' },
  '琴': { strokes: 13, meaning: '거문고', reading: '금' },
  '千': { strokes: 3, meaning: '일천', reading: '천' },
  '魯': { strokes: 15, meaning: '나라', reading: '노' },
  '殷': { strokes: 10, meaning: '은나라', reading: '은' },
  '片': { strokes: 4, meaning: '조각', reading: '편' },
  '甘': { strokes: 5, meaning: '달', reading: '감' },
  '吉': { strokes: 6, meaning: '길할', reading: '길' },
  '都': { strokes: 12, meaning: '도읍', reading: '도' },
  '夫': { strokes: 4, meaning: '지아비', reading: '부' },
  '陰': { strokes: 11, meaning: '그늘', reading: '음' },
  '王': { strokes: 4, meaning: '임금', reading: '왕' },
  '秦': { strokes: 10, meaning: '나라', reading: '진' },
};

// ============================================================
// 추가 보충 한자 (기타 작명에 쓰이는 한자)
// ============================================================
const SUPPLEMENTARY: Record<string, HanjaEntry> = {
  '佑': { strokes: 7, meaning: '도울', reading: '우' },
  '俐': { strokes: 9, meaning: '영리할', reading: '리' },
  '倖': { strokes: 10, meaning: '요행', reading: '행' },
  '健': { strokes: 11, meaning: '건강할', reading: '건' },
  '傑': { strokes: 13, meaning: '뛰어날', reading: '걸' },
  '優': { strokes: 17, meaning: '넉넉할', reading: '우' },
  '克': { strokes: 7, meaning: '이길', reading: '극' },
  '凡': { strokes: 3, meaning: '무릇', reading: '범' },
  '劭': { strokes: 7, meaning: '힘쓸', reading: '소' },
  '勉': { strokes: 9, meaning: '힘쓸', reading: '면' },
  '勤': { strokes: 13, meaning: '부지런할', reading: '근' },
  '卓': { strokes: 8, meaning: '높을', reading: '탁' },
  '協': { strokes: 8, meaning: '화합할', reading: '협' },
  '南': { strokes: 9, meaning: '남녘', reading: '남' },
  '叡': { strokes: 16, meaning: '슬기로울', reading: '예' },
  '台': { strokes: 5, meaning: '별', reading: '태' },
  '合': { strokes: 6, meaning: '합할', reading: '합' },
  '向': { strokes: 6, meaning: '향할', reading: '향' },
  '哲': { strokes: 10, meaning: '밝을', reading: '철' },
  '唯': { strokes: 11, meaning: '오직', reading: '유' },
  '啓': { strokes: 11, meaning: '열', reading: '계' },
  '嗣': { strokes: 13, meaning: '이을', reading: '사' },
  '圓': { strokes: 13, meaning: '둥글', reading: '원' },
  '坊': { strokes: 7, meaning: '마을', reading: '방' },
  '壯': { strokes: 7, meaning: '장할', reading: '장' },
  '奉': { strokes: 8, meaning: '받들', reading: '봉' },
  '奎': { strokes: 9, meaning: '별', reading: '규' },
  '奮': { strokes: 16, meaning: '떨칠', reading: '분' },
  '宏': { strokes: 7, meaning: '클', reading: '굉' },
  '宙': { strokes: 8, meaning: '집', reading: '주' },
  '宥': { strokes: 9, meaning: '너그러울', reading: '유' },
  '寅': { strokes: 11, meaning: '범', reading: '인' },
  '岳': { strokes: 8, meaning: '큰 산', reading: '악' },
  '嶺': { strokes: 17, meaning: '고개', reading: '령' },
  '帝': { strokes: 9, meaning: '임금', reading: '제' },
  '幸': { strokes: 8, meaning: '다행', reading: '행' },
  '庸': { strokes: 11, meaning: '쓸', reading: '용' },
  '弘': { strokes: 5, meaning: '클', reading: '홍' },
  '得': { strokes: 11, meaning: '얻을', reading: '득' },
  '恕': { strokes: 10, meaning: '용서할', reading: '서' },
  '悟': { strokes: 11, meaning: '깨달을', reading: '오' },
  '惇': { strokes: 12, meaning: '도타울', reading: '돈' },
  '愼': { strokes: 14, meaning: '삼갈', reading: '신' },
  '慕': { strokes: 15, meaning: '사모할', reading: '모' },
  '憬': { strokes: 16, meaning: '깨달을', reading: '경' },
  '懋': { strokes: 17, meaning: '힘쓸', reading: '무' },
  '拓': { strokes: 9, meaning: '넓힐', reading: '척' },
  '振': { strokes: 11, meaning: '떨칠', reading: '진' },
  '揚': { strokes: 13, meaning: '날릴', reading: '양' },
  '政': { strokes: 8, meaning: '정사', reading: '정' },
  '斗': { strokes: 4, meaning: '말', reading: '두' },
  '昊': { strokes: 8, meaning: '하늘', reading: '호' },
  '晃': { strokes: 10, meaning: '밝을', reading: '황' },
  '暢': { strokes: 14, meaning: '통할', reading: '창' },
  '曙': { strokes: 18, meaning: '새벽', reading: '서' },
  '朔': { strokes: 10, meaning: '초하루', reading: '삭' },
  '柄': { strokes: 9, meaning: '자루', reading: '병' },
  '棋': { strokes: 12, meaning: '바둑', reading: '기' },
  '楷': { strokes: 13, meaning: '법', reading: '해' },
  '樂': { strokes: 15, meaning: '즐거울', reading: '락' },
  '欽': { strokes: 12, meaning: '공경할', reading: '흠' },
  '殿': { strokes: 13, meaning: '전', reading: '전' },
  '汎': { strokes: 7, meaning: '넓을', reading: '범' },
  '沂': { strokes: 8, meaning: '강이름', reading: '기' },
  '治': { strokes: 9, meaning: '다스릴', reading: '치' },
  '浹': { strokes: 11, meaning: '젖을', reading: '협' },
  '琥': { strokes: 13, meaning: '호박', reading: '호' },
  '璨': { strokes: 18, meaning: '옥빛', reading: '찬' },
  '甫': { strokes: 7, meaning: '클', reading: '보' },
  '相': { strokes: 9, meaning: '서로', reading: '상' },
  '碩': { strokes: 14, meaning: '클', reading: '석' },
  '磊': { strokes: 15, meaning: '돌 쌓일', reading: '뢰' },
  '穆': { strokes: 16, meaning: '화목할', reading: '목' },
  '立': { strokes: 5, meaning: '설', reading: '립' },
  '端': { strokes: 14, meaning: '바를', reading: '단' },
  '笙': { strokes: 11, meaning: '생황', reading: '생' },
  '策': { strokes: 12, meaning: '꾀', reading: '책' },
  '絃': { strokes: 11, meaning: '줄', reading: '현' },
  '纘': { strokes: 26, meaning: '이을', reading: '찬' },
  '翔': { strokes: 12, meaning: '날', reading: '상' },
  '耀': { strokes: 20, meaning: '빛날', reading: '요' },
  '致': { strokes: 10, meaning: '이를', reading: '치' },
  '興': { strokes: 16, meaning: '일어날', reading: '흥' },
  '衍': { strokes: 9, meaning: '넘칠', reading: '연' },
  '裕': { strokes: 13, meaning: '넉넉할', reading: '유' },
  '覺': { strokes: 20, meaning: '깨달을', reading: '각' },
  '諺': { strokes: 16, meaning: '속담', reading: '언' },
  '謙': { strokes: 17, meaning: '겸손할', reading: '겸' },
  '讚': { strokes: 26, meaning: '기릴', reading: '찬' },
  '贊': { strokes: 19, meaning: '도울', reading: '찬' },
  '赫': { strokes: 14, meaning: '빛날', reading: '혁' },
  '軒': { strokes: 10, meaning: '집', reading: '헌' },
  '述': { strokes: 8, meaning: '이을', reading: '술' },
  '逢': { strokes: 14, meaning: '만날', reading: '봉' },
  '達': { strokes: 16, meaning: '통달할', reading: '달' },
  '運': { strokes: 16, meaning: '운', reading: '운' },
  '錄': { strokes: 16, meaning: '기록할', reading: '록' },
  '隆': { strokes: 17, meaning: '클', reading: '륭' },
  '雲': { strokes: 12, meaning: '구름', reading: '운' },
  '顯': { strokes: 23, meaning: '나타날', reading: '현' },
  '馨': { strokes: 20, meaning: '향기', reading: '형' },
  '驥': { strokes: 27, meaning: '천리마', reading: '기' },
  '鶴': { strokes: 21, meaning: '학', reading: '학' },
  '鳳': { strokes: 14, meaning: '봉황', reading: '봉' },
  '麟': { strokes: 23, meaning: '기린', reading: '린' },
  '齊': { strokes: 14, meaning: '가지런할', reading: '제' },
};

// ============================================================
// 전체 데이터베이스 병합 (중복 키는 뒤의 것이 우선)
// ============================================================

// 오행 그룹에 element 필드를 부여하는 헬퍼
function withElement(
  group: Record<string, HanjaEntry>,
  element: HanjaEntry['element'],
): Record<string, HanjaEntry> {
  const result: Record<string, HanjaEntry> = {};
  for (const [char, entry] of Object.entries(group)) {
    result[char] = { ...entry, element };
  }
  return result;
}

export const HANJA_STROKE_DB: Record<string, HanjaEntry> = {
  ...SURNAMES,
  ...UNISEX_COMMON,
  ...withElement(WOOD_ELEMENT, '木'),
  ...withElement(FIRE_ELEMENT, '火'),
  ...withElement(EARTH_ELEMENT, '土'),
  ...withElement(METAL_ELEMENT, '金'),
  ...withElement(WATER_ELEMENT, '水'),
  ...MALE_COMMON,
  ...FEMALE_COMMON,
  ...SUPPLEMENTARY,
};

/**
 * 한자의 획수를 조회합니다.
 * DB에 있으면 정확한 획수를, 없으면 유니코드 기반 추정값을 반환합니다.
 */
export function getHanjaStrokes(char: string): number {
  const entry = HANJA_STROKE_DB[char];
  if (entry) {
    return entry.strokes;
  }

  // DB에 없는 한자: 유니코드 CJK 범위 기반 추정 (fallback)
  const code = char.charCodeAt(0);
  if (code >= 0x4E00 && code <= 0x9FFF) {
    // CJK Unified Ideographs 범위: 대략적 추정
    // 부수 복잡도 기반 간이 추정 (정확하지 않으므로 경고 로그)
    console.warn(
      `[hanja-strokes] "${char}" (U+${code.toString(16).toUpperCase()})은(는) DB에 없습니다. 유니코드 기반 추정값을 사용합니다.`
    );
    // 통계적으로 한자의 평균 획수는 약 10-12획
    // 코드 포인트 위치 기반으로 대략적 추정 (낮은 코드 = 간단한 글자 경향)
    const normalized = (code - 0x4E00) / (0x9FFF - 0x4E00);
    return Math.round(6 + normalized * 14);
  }

  // 한글이나 기타 문자인 경우 기본값
  console.warn(
    `[hanja-strokes] "${char}"은(는) 한자가 아닙니다. 기본값 1을 사용합니다.`
  );
  return 1;
}

/**
 * 한자의 상세 정보를 조회합니다.
 * DB에 없으면 null을 반환합니다.
 */
export function getHanjaEntry(char: string): HanjaEntry | null {
  return HANJA_STROKE_DB[char] ?? null;
}

// DB 통계 (개발/디버그 용도)
export const HANJA_DB_SIZE = Object.keys(HANJA_STROKE_DB).length;
